{% set name = "perl-b-hooks-endofscope" %}
{% set version = "0.27" %}
{% set sha256 = "106bac2dc33fb8f9bf8481dc8bbf2128fa486e7ee77e083fcfa176e62aa4f82c" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/E/ET/ETHER/B-Hooks-EndOfScope-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: true  # [win]
  number: 0
  run_exports:
    weak:
      - {{ name }} ={{ version }}

requirements:
  build:
    - make
  host:
    - perl
    - perl-sub-exporter-progressive
    - perl-module-implementation
    - perl-variable-magic
  run:
    - perl

test:
  imports:
    - B::Hooks::EndOfScope
    - B::Hooks::EndOfScope::PP
    - B::Hooks::EndOfScope::XS

about:
  home: https://github.com/karenetheridge/B-Hooks-EndOfScope
  license: GPL-1.0-or-later OR Artistic-1.0-Perl
  license_file:
    - {{ environ["PREFIX"] }}/man/man1/perlartistic.1
    - {{ environ["PREFIX"] }}/man/man1/perlgpl.1
  summary: 'Execute code after a scope finished compilation'

extra:
  recipe-maintainers:
    - xileF1337
    - conda-forge/perl-packagers
